use_frameworks!

target 'ListrakSDK_Example' do
  pod 'ListrakSDK', :path => '../'

  target 'ListrakSDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'OCMockito', '~> 4.0'
  end
end
